### ISSUE TITLE
git lfs error

### ISSUE THREAD

**Issue by peyer** [inferenceengine/shadernn#1] opened 2022-10-30 06:38 UTC
Downloading core/3rdparty/glfw/lib64/glfw3.dll (226 KB)
Error downloading object: core/3rdparty/glfw/lib64/glfw3.dll (f563382): Smudge error: Error downloading core/3rdparty/glfw/lib64/glfw3.dll (f5633822089c03f6d11442b6a18de2f0f40a7d425552b90bebe64e5e5c93a1bf): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by inferenceengine** [comment] 2022-11-16 00:30
The LFS bandwidth is increased and it should work now. Thanks.

**Comment by inferenceengine** [comment] 2022-12-16 21:04
It is verified that the issue is resolved by users.

**Closed as completed by inferenceengine** 2022-12-16 21:04 UTC
